// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tenanpp.Repository;


namespace dotnet_app.Migrations
{
    [DbContext(typeof(TenanppContext))]
    [Migration("20191121032316_SeedInmobiliarias")]
    partial class SeedInmobiliarias
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tenanpp.Models.Inmobiliaria", b =>
                {
                    b.Property<long>("InmobiliariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cuit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InmobiliariaId");

                    b.ToTable("Inmobiliarias");

                    b.HasData(
                        new
                        {
                            InmobiliariaId = 1L,
                            Cuit = "30-5212367-12",
                            Direccion = "Directorio 3456",
                            Localidad = "Capital Federal",
                            Nombre = "Lepore",
                            Telefono = "011 44339820",
                            Url = "https://www.lepore.com.ar"
                        },
                        new
                        {
                            InmobiliariaId = 2L,
                            Cuit = "30-278901500-33",
                            Direccion = "Rivadavia 9876",
                            Localidad = "Capital Federal",
                            Nombre = "Juan Propiedades",
                            Telefono = "011 4468 9320",
                            Url = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
