// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tenanpp.Repository;

namespace dotnet_app.Migrations
{
    [DbContext(typeof(TenanppContext))]
    partial class TenanppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tenanpp.Models.Inmobiliaria", b =>
                {
                    b.Property<long>("InmobiliariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cuit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InmobiliariaId");

                    b.ToTable("Inmobiliarias");

                    b.HasData(
                        new
                        {
                            InmobiliariaId = 1L,
                            Cuit = "30-5212367-12",
                            Direccion = "Directorio 3456",
                            Localidad = "Capital Federal",
                            Nombre = "Lepore",
                            Telefono = "011 44339820",
                            Url = "https://www.lepore.com.ar"
                        },
                        new
                        {
                            InmobiliariaId = 2L,
                            Cuit = "30-278901500-33",
                            Direccion = "Rivadavia 9876",
                            Localidad = "Capital Federal",
                            Nombre = "Juan Propiedades",
                            Telefono = "011 4468 9320",
                            Url = ""
                        });
                });

            modelBuilder.Entity("Tenanpp.Models.OpinionInmobiliaria", b =>
                {
                    b.Property<int>("OpinionInmobiliariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("FechaOpinion")
                        .HasColumnType("datetime2");

                    b.Property<long>("InmobiliariaId")
                        .HasColumnType("bigint");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valoracion")
                        .HasColumnType("int");

                    b.HasKey("OpinionInmobiliariaId");

                    b.HasIndex("InmobiliariaId");

                    b.ToTable("OpinionesInmobiliarias");
                });

            modelBuilder.Entity("Tenanpp.Models.OpinionInmobiliaria", b =>
                {
                    b.HasOne("Tenanpp.Models.Inmobiliaria", "Inmobiliaria")
                        .WithMany()
                        .HasForeignKey("InmobiliariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
